### ISSUE TITLE
Implement following dependencies 

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/SpiceQL#79]
Although solving frame chain is more of an ALE problem, we need an API for determining the required kernels for computing orientations to/from arbitrary frames. This basically just means find an implementation for the dep group in the JSON which currently are not really being used. 

This will most likely depend on https://github.com/USGS-Astrogeology/SugarSpice/issues/75 as it requires resolving kernels from different config files.

**Comment by jessemapel** [comment]
closed by #122
